DROP TABLE IF EXISTS posts;

CREATE TABLE posts (
    id SERIAL PRIMARY KEY,
    title text NOT NULL,
    description TEXT NOT NULL,
    body TEXT NOT NULL
);

INSERT INTO posts
    (title, description, body)
VALUES
    ('Title 1', '1st Blog Post', 'Emerged into consciousness extraplanetary paroxysm of global death another world muse about bits of moving fluff. Permanence of the stars rings of Uranus vastness is bearable only through love network of wormholes the carbon in our apple pies tingling of the spine. The only home we''ve ever known star stuff harvesting star light a mote of dust suspended in a sunbeam brain is the seed of intelligence as a patch of light with pretty stories for which there''s little good evidence and billions upon billions upon billions upon billions upon billions upon billions upon billions.'),

    ('Title 2', '2nd Blog Post', 'Boatswain Sea Legs Pieces of Eight maroon jack bring a spring upon her cable spanker fluke scurvy poop deck. Me long boat tackle clap of thunder spanker Pirate Round dead men tell no tales killick rum bucko. Holystone rope''s end bounty broadside Sea Legs parrel reef measured fer yer chains quarter pinnace. Shrouds reef skysail Davy Jones'' Locker pirate bring a spring upon her cable ho red ensign to go on account overhaul. Square-rigged reef avast topmast handsomely brigantine hail-shot spike American Main pirate. Line Yellow Jack spike long clothes gabion wherry fathom code of conduct poop deck mizzen. Jolly boat lateen sail fore gabion splice the main brace gibbet holystone hardtack ballast lugger. Sutler Buccaneer league barkadeer jack chase guns nipper cackle fruit hulk topsail. Jolly boat mizzenmast boom boatswain landlubber or just lubber booty blow the man down deadlights gunwalls mutiny.'),

    ('Title 3', '3rd Blog Post', 'Cupcake ipsum dolor sit amet marzipan brownie carrot cake. Pastry oat cake sugar plum gingerbread fruitcake. Brownie wafer wafer fruitcake. Danish tootsie roll topping apple pie liquorice sweet roll cotton candy cookie candy canes. Chocolate cake pastry gingerbread cookie marshmallow pudding bear claw chocolate marshmallow. Wafer donut icing cookie tiramisu caramels lemon drops candy. Gummies tiramisu cotton candy jujubes brownie macaroon cookie brownie. Lollipop cake chocolate wafer cheesecake muffin dragée marshmallow ice cream. Chocolate cake cake jelly-o muffin dragée marshmallow tart gummi bears. Halvah dragée gummies dragée gingerbread bear claw cotton candy lollipop. Dessert powder jelly-o marshmallow macaroon jujubes donut sweet roll. Jelly-o cake bonbon danish marshmallow lemon drops caramels. Chocolate cake cake sesame snaps tart chocolate. Pie liquorice cupcake sweet roll croissant donut jelly jelly beans tiramisu.'),

    ('Title 4', '4th Blog Post', 'I love cheese, especially cheese triangles manchego. Cow cheese triangles fromage cream cheese stinking bishop cream cheese cream cheese cheese slices. Rubber cheese caerphilly pecorino boursin feta pepper jack the big cheese red leicester. Mascarpone feta cheeseburger the big cheese goat cow airedale gouda. Mozzarella cheese triangles brie goat bavarian bergkase edam pecorino cheesy grin. Chalk and cheese cheese strings pecorino caerphilly who moved my cheese cheese triangles fromage frais camembert de normandie. Gouda everyone loves mascarpone fromage smelly cheese red leicester cheeseburger feta. Cheesy grin smelly cheese monterey jack cheesy feet cottage cheese babybel rubber cheese feta. Cheeseburger manchego cut the cheese who moved my cheese danish fontina hard cheese melted cheese chalk and cheese. The big cheese gouda fromage.'),

    ('Title 5', '5th Blog Post', 'I''ll tell them you went down prying the wedding ring off his cold, dead finger. We''re rescuing ya. Really?! No, she''ll probably make me do it. Fetal stemcells, aren''t those controversial? Then we''ll go with that data file! Oh, I think we should just stay friends. Oh yeah, good luck with that. Your best is an idiot! Yes! In your face, Gandhi! I feel like I was mauled by Jesus. I''ll tell them you went down prying the wedding ring off his cold, dead finger. It''s a T. It goes tuh. Of all the friends I''ve had… you''re the first. Hey, what kinda party is this? There''s no booze and only one hooker. Do a flip! Now what? It''s just like the story of the grasshopper and the octopus. All year long, the grasshopper kept burying acorns for winter, while the octopus mooched off his girlfriend and watched TV. But then the winter came, and the grasshopper died, and the octopus ate all his acorns. Also he got a race car. Is any of this getting through to you? Bite my shiny metal ass. I wish! It''s a nickel. Guards! Bring me the forms I need to fill out to have her taken away! Soothe us with sweet lies. I didn''t ask for a completely reasonable excuse! I asked you to get busy! For one beautiful night I knew what it was like to be a grandmother. Subjugated, yet honored. Would you censor the Venus de Venus just because you can see her spewers? Ok, we''ll go deliver this crate like professionals, and then we''ll go ride the bumper cars.'),

    ('Title 6', '6th Blog Post', '3 wolf moon incididunt pickled flannel adipisicing glossier chambray, bespoke kinfolk et nisi. Selfies austin iPhone woke distillery succulents, organic kitsch PBR&B stumptown actually kogi church-key. Raclette master cleanse pug austin organic. Normcore hella jean shorts taxidermy, duis twee beard typewriter live-edge ad aesthetic ennui raclette literally tote bag.'),

    ('Title 7', '7th Blog Post', 'Cat ipsum dolor sit amet, flex claws on the human''s belly and purr like a lawnmower. do not try to mix old food with new one to fool me! get poop stuck in paws jumping out of litter box and run around the house scream meowing and smearing hot cat mud all over jump five feet high and sideways when a shadow moves. Pet me pet me pet me pet me, bite, scratch, why are you petting me then cats take over the world jump up to edge of bath, fall in then scramble in a mad panic to get out catch mouse and gave it as a present. Have a lot of grump in yourself because you can''t forget to be grumpy and not be like king grumpy cat. Paw your face to wake you up in the morning get suspicious of own shadow then go play with toilette paper but purr for no reason cats go for world domination attack the child. Eat a plant, kill a hand chew master''s slippers yet chew on cable for get poop stuck in paws jumping out of litter box and run around the house scream meowing and smearing hot cat mud all over. Burrow under covers. Oooo! dangly balls! jump swat swing flies so sweetly to the floor crash move on wash belly nap eat the fat cats food mice missing until dinner time, or leave buried treasure in the sandbox for the toddlers yet woops poop hanging from butt must get rid run run around house drag poop on floor maybe it comes off woops left brown marks on floor human slave clean lick butt now. Cats woo lie on your belly and purr when you are asleep or groom forever, stretch tongue and leave it slightly out, blep. Eat fish on floor drink from the toilet or murr i hate humans they are so annoying yet gnaw the corn cob rub against owner because nose is wet stare out cat door then go back inside.');